services:
  pms-dashboard:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: pms-dashboard
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "const http = require('http'); const options = { host: 'localhost', port: 3000, path: '/health', timeout: 2000 }; const req = http.request(options, (res) => { console.log('STATUS: ' + res.statusCode); process.exitCode = (res.statusCode === 200) ? 0 : 1; }); req.on('error', () => process.exitCode = 1); req.on('timeout', () => process.exitCode = 1); req.end();"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "com.docker.compose.project=pms-dashboard"
      - "description=Performance Management System Dashboard"

networks:
  default:
    name: pms-network